services:
  server:
    container_name: server
    build:
      context: ./server
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb://localhost:27017
      - MONGO_MIN_POOL=10
      - MONGO_MAX_POOL=100
      - MONGO_MAX_CONN_IDLE=60
      - MONGO_DATABASE=urlShortener
      - URL_COLLECTION=urls
      - USER_COLLECTION=users
      - JWT_SECRET=SECRET
      - JWT_LIFE=6
      - STAGE=PRODUCTION
    networks:
      - app-network
    restart: unless-stopped

  client:
    container_name: client
    build:
      context: ./client
      args:
        - API_ENDPOINT=https://domain.tld/go
    ports:
      - 3000:3000
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - server

  web-server:
    container_name: web-server
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fullchain.pem:/etc/nginx/fullchain.pem
      - ./privkey.pem:/etc/nginx/privkey.pem
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - server
      - client

networks:
  app-network:
    name: app-network
