version: '3.8'

services:
  api-spec:
    container_name: api-spec
    image: swaggerapi/swagger-ui:v3.52.2
    ports:
      - 8080:8080
    environment:
      - SWAGGER_JSON=/data/api-spec.yaml
    volumes:
      - ./server/api-spec.yaml:/data/api-spec.yaml
    networks:
      - url-shortener
    restart: unless-stopped

  database:
    container_name: database
    image: mongo:5.0.4
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb:/data/db
    networks:
      - url-shortener
    restart: unless-stopped
    depends_on:
      - api-spec

  server:
    container_name: server
    build:
      context: ./server
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb://root:password@database:27017
      - MONGO_MIN_POOL=10
      - MONGO_MAX_POOL=100
      - MONGO_MAX_CONN_IDLE=60
      - MONGO_DATABASE=urlShortener
      - URL_COLLECTION=urls
      - DOMAIN=https://domain.tld
    networks:
      - url-shortener
    restart: unless-stopped
    depends_on:
      - api-spec
      - database

  client:
    container_name: client
    build:
      context: ./client
      args:
        - API_ENDPOINT=https://domain.tld/api/v1/go
        - DOMAIN=https://domain.tld
    ports:
      - 3000:3000
    networks:
      - url-shortener
    restart: unless-stopped
    depends_on:
      - api-spec
      - database
      - server

  web-server:
    container_name: web-server
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fullchain.pem:/etc/nginx/fullchain.pem
      - ./privkey.pem:/etc/nginx/privkey.pem
    networks:
      - url-shortener
    restart: unless-stopped
    depends_on:
      - api-spec
      - database
      - server
      - client

volumes:
  mongodb:

networks:
  url-shortener:
    name: url-shortener
